# Stage 1: Build the React Electron frontend
#FROM node:18-alpine as frontend
FROM mcr.microsoft.com/devcontainers/base:jammy

# Set environment variables to avoid prompts during installation
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /workspace

# Update the package lists for upgrades and new package installations
RUN apt-get update \
    && apt-get install -y libglib2.0-0 libnss3 libdbus-1-3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgtk-3-0 libgbm1 libasound2 \
    && apt-get install -y curl \
    #&& apt-get install -y gnupg \
    #&& apt-get install -y python3 \
    #&& apt-get install -y python3-pip \
    #&& apt-get install -y libdbus-1-3 \
    #&& apt-get install -y libatk1.0-0 \
    #&& apt-get install -y libatk-bridge2.0-0 \
    #&& apt-get install -y libcups2 \
    #&& apt-get install -y libgtk-3-0 \
    #&& apt-get install -y libgbm1 \
    #&& apt-get install -y libasound2 \
    #&& apt-get install -y libnss3 \
    #&& apt-get install -y xvfb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#RUN service dbus start

# Add NodeSource APT repository for Node.js 20
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

# Install dependencies
#COPY electron-react-frontend/package.json electron-react-frontend/package-lock.json ./
COPY . .
RUN npm install --prefix electron-react-frontend

EXPOSE 5173
#RUN npm --prefix electron-react-frontend run dev
